FROM ubuntu:16.04
RUN apt-get update --assume-yes && apt-get install --assume-yes gcc python3-dev python3-pip
RUN pip3 install psutil
RUN apt-get update --assume-yes && apt-get install --assume-yes openjdk-8-jdk
