"""empty message

Revision ID: 03adcd268b1a
Revises: d16f27a58073
Create Date: 2016-10-19 15:22:49.078953

"""

# revision identifiers, used by Alembic.
revision = '03adcd268b1a'
down_revision = 'd16f27a58073'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column('value', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('language', 'value')
    ### end Alembic commands ###
