"""empty message

Revision ID: 0df9d50aa0ca
Revises: 3305c9149289
Create Date: 2016-11-02 18:08:32.322452

"""

# revision identifiers, used by Alembic.
revision = '0df9d50aa0ca'
down_revision = '3305c9149289'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case', sa.Column('is_sample', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'is_sample')
    ### end Alembic commands ###
