"""empty message

Revision ID: 21f531c2c2e3
Revises: 757031c276e5
Create Date: 2016-09-22 22:46:46.096285

"""

# revision identifiers, used by Alembic.
revision = '21f531c2c2e3'
down_revision = '757031c276e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('group_id', sa.Integer(), nullable=True))
    op.drop_constraint('enrollment_teacher_id_fkey', 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'group', ['group_id'], ['id'])
    op.drop_column('enrollment', 'teacher_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'enrollment', type_='foreignkey')
    op.create_foreign_key('enrollment_teacher_id_fkey', 'enrollment', 'user', ['teacher_id'], ['id'])
    op.drop_column('enrollment', 'group_id')
    ### end Alembic commands ###
