"""empty message

Revision ID: 41e4e92f91a6
Revises: 647291ea6ec7
Create Date: 2016-10-05 15:30:37.292420

"""

# revision identifiers, used by Alembic.
revision = '41e4e92f91a6'
down_revision = '647291ea6ec7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('professor_id', sa.Integer(), nullable=True))
    op.drop_constraint('group_teacher_id_fkey', 'group', type_='foreignkey')
    op.create_foreign_key(None, 'group', 'user', ['professor_id'], ['id'])
    op.drop_column('group', 'teacher_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.create_foreign_key('group_teacher_id_fkey', 'group', 'user', ['teacher_id'], ['id'])
    op.drop_column('group', 'professor_id')
    ### end Alembic commands ###
