"""empty message

Revision ID: 4e8e2efbe395
Revises: 11b519e9e44c
Create Date: 2016-11-01 17:15:58.385170

"""

# revision identifiers, used by Alembic.
revision = '4e8e2efbe395'
down_revision = '11b519e9e44c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'problem', 'user', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problem', type_='foreignkey')
    op.drop_column('problem', 'author_id')
    ### end Alembic commands ###
