"""empty message

Revision ID: 68d2bcfe12a3
Revises: bc6f8222c86b
Create Date: 2016-10-21 00:10:18.682291

"""

# revision identifiers, used by Alembic.
revision = '68d2bcfe12a3'
down_revision = 'bc6f8222c86b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('description_english', sa.Text(), nullable=True))
    op.add_column('problem', sa.Column('description_spanish', sa.Text(), nullable=True))
    op.drop_column('problem', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('problem', 'description_spanish')
    op.drop_column('problem', 'description_english')
    ### end Alembic commands ###
