"""empty message

Revision ID: 839b2982db1f
Revises: dde8e741cef3
Create Date: 2016-11-07 13:25:54.991123

"""

# revision identifiers, used by Alembic.
revision = '839b2982db1f'
down_revision = 'dde8e741cef3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem', sa.Column('signature', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problem', 'signature')
    ### end Alembic commands ###
