"""empty message

Revision ID: 8aaa54384776
Revises: 839b2982db1f
Create Date: 2016-11-29 18:06:51.782267

"""

# revision identifiers, used by Alembic.
revision = '8aaa54384776'
down_revision = '839b2982db1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('no_of_attempt', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'no_of_attempt')
    ### end Alembic commands ###
