"""empty message

Revision ID: bc6f8222c86b
Revises: d20009ded56e
Create Date: 2016-10-20 23:09:12.013446

"""

# revision identifiers, used by Alembic.
revision = 'bc6f8222c86b'
down_revision = 'd20009ded56e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('feedback_list', sa.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'feedback_list')
    ### end Alembic commands ###
