"""empty message

Revision ID: d16f27a58073
Revises: 41e4e92f91a6
Create Date: 2016-10-19 15:20:50.479926

"""

# revision identifiers, used by Alembic.
revision = 'd16f27a58073'
down_revision = '41e4e92f91a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language')
    ### end Alembic commands ###
