"""empty message

Revision ID: d20009ded56e
Revises: eaabedb41e5d
Create Date: 2016-10-20 23:08:34.312076

"""

# revision identifiers, used by Alembic.
revision = 'd20009ded56e'
down_revision = 'eaabedb41e5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'feedback')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
