"""empty message

Revision ID: d9c3f6ad5c1a
Revises: 03adcd268b1a
Create Date: 2016-10-20 20:18:52.710459

"""

# revision identifiers, used by Alembic.
revision = 'd9c3f6ad5c1a'
down_revision = '03adcd268b1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'state')
    op.drop_column('submission', 'result')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('result', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('submission', sa.Column('state', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
